# Generated by Django 5.2.4 on 2026-08-10 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_alter_lead_assigned_user_alter_lead_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='phone',
            field=models.BigIntegerField(blank=True, max_length=10, null=True),
        ),
    ]
