# Generated by Django 6.0.7 on 2026-07-17 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('source', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=50)),
                ('notes', models.TextField(blank=True)),
            ],
        ),
    ]
